[project]
name = "dataflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow==2.7.3",
    "apache-airflow-providers-celery==3.0.0",
    "apache-airflow-providers-docker==3.0.0",
    "celery[redis]>=5.6.0",
    "flower==1.0.0",
    "importlib-metadata==4.13.0",
    "loguru>=0.7.3",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pymysql>=1.1.2",
]
