format:
	black -l 40 upload_data2mysql.py

download-taiwan-stock-info:
	uv run python upload_data2mysql.py taiwan_stock_info

download-taiwan-stock-price:
	uv run python upload_data2mysql.py taiwan_stock_price

download-taiwan-stock-institutional-investors:
	uv run python upload_data2mysql.py taiwan_stock_institutional_investors

download-taiwan-stock-margin-purchase-short_sale:
	uv run python upload_data2mysql.py taiwan_stock_margin_purchase_short_sale

download-taiwan-stock-holding-shares-per:
	uv run python upload_data2mysql.py taiwan_stock_holding_shares_per
