version: '3.0'
services:
  scheduler:
    image: crawler3:7.2.1
    hostname: "twse"
    command: uv run  --env-file=.env python -m financialdata.scheduler
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true
