format:
	black -l 40 upload_data2mysql.py

download-taiwan-stock-info:
	pipenv run python upload_data2mysql.py taiwan_stock_info

download-taiwan-stock-price:
	pipenv run python upload_data2mysql.py taiwan_stock_price
