version: '3.7'

volumes:
    prometheus_data: {}
    
services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - net

  netdata:
    restart: always
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    image: netdata/netdata:v1.31.0
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - net

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    user: root
    restart: always
    networks:
        - net

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    user: root
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    restart: always
    networks:
        - net

networks:
  net:
