FROM grafana/grafana:10.4.3
COPY ./grafana/provisioning /etc/grafana/provisioning
COPY ./grafana/grafana.ini /etc/grafana/grafana.ini
COPY ./grafana/grafana-piechart-panel /usr/share/grafana/plugins-bundled/internal/piechart-panel
