FROM grafana/grafana:8.5.25
COPY ./grafana/provisioning /etc/grafana/provisioning
COPY ./grafana/grafana.ini /etc/grafana/grafana.ini
COPY ./grafana/grafana-piechart-panel /usr/share/grafana/plugins-bundled/internal/piechart-panel
